#!/bin/bash

# Update registry settings.
# Set Wine to Vista for Logos indexer.
"${WINELOADER}" reg add "HKCU\\Software\\Wine\\AppDefaults\\LogosIndexer.exe" \
    /v Version /t REG_SZ /d vista /f

# Symlink to $LOGOS_DATA.
logos_win_path="drive_c/users/$USER/Local Settings/Application Data/Logos"
LOGOS_DATA="$HOME/.logos-data"
mkdir -p "$LOGOS_DATA"
LOGOS32_FOLDER="$HOME/.wine-logos/${logos_win_path}"
LOGOS_SNAP_FOLDER="${WINEPREFIX}/${logos_win_path}"
CONTENT_DIRS=( "Data" "Documents" "Users" )
prefix_dirs=( "$LOGOS32_FOLDER" "$LOGOS_SNAP_FOLDER" )
for c in "${CONTENT_DIRS[@]}"; do
    for p in "${prefix_dirs[@]}"; do
        rm -rf "${p}/${c}"
        ln -s "$LOGOS_DATA/${c}" "${p}/${c}"
    done
done
