name: cardsorter
base: core18
version: '0.1'
summary: Sort words according to varous linguistic features
description: |
  Sort words according to varous linguistic features

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  cardsorter:
    command: opt/wine-stable/bin/wine64 opt/bin/cardsorter

  wine:
    command: opt/wine-stable/bin/wine64

parts:
  cardsorter:
    plugin: dump
    source: .
    build-packages:
      - unzip
      - wine-stable
    # build-snaps:
    #   - wine-platform-6-stable
    override-build: |
      # Add 32-bit arch for wine.
      dpkg --add-architecture i386
      apt-get update --yes
      apt-get install wine32 --yes

      # Run Setup.
      unzip CardSorterWPF20211111.zip
      wine64 setup.exe
    stage-snaps:
      - wine-platform-6-stable
