name: saymore
title: SayMore
version: '3.2.22' # matches installer version below
summary: SayMore
description: |
  SayMore

  *Note: This Windows application runs on Linux using the Wine compatibility layer.*
grade: devel
# icon: snap/gui/tmnationsforever.png

confinement: devmode
base: core20

architectures:
  - amd64

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml=" # block Wine Mono and Wine Gecko pop-ups
  TRICKS: "dotnet48"

apps:
  saymore:
    command: bin/sommelier run-exe
    extensions: [gnome-3-38]
    environment:
      RUN_EXE: "C:/Program Files (x86)/SayMore/SayMore.exe"
      INSTALL_URL: "https://software.sil.org/downloads/r/saymore/SayMoreInstaller.3.2.22.msi"
      # INSTALL_FLAGS: "/silent"
      # SOMMELIER_VIRTDESKTOP: 1
    plugs:
      - home
      - network
      - opengl
      - audio-playback

  wine:
    command: bin/sommelier
    extensions: [gnome-3-38]
    plugs:
      - home
      - network

  winecfg:
    command: bin/sommelier winecfg
    extensions: [gnome-3-38]
    # plugs:
      # - home
      # - network

  winetricks:
    command: bin/sommelier winetricks
    extensions: [gnome-3-38]
    plugs:
      - network

parts:
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    override-prime: |
      snapcraftctl prime

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # Remove annoying yad dialog for interactive MSI install.
      sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier


# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20

  wine-7-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core20
