name: saymore
title: SayMore
version: '3.2.22'
summary: SayMore
description: |
  SayMore

  *Note: This Windows application runs on Linux using the Wine compatibility layer.*
grade: devel
# icon: snap/gui/tmnationsforever.png

confinement: devmode
base: core18

architectures:
  - amd64

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  saymore:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files/SayMore/SayMore.exe"
      INSTALL_URL: "https://software.sil.org/downloads/r/saymore/SayMoreInstaller.${SNAP_VERSION}.msi"
      # INSTALL_FLAGS: "/silent"
      # SOMMELIER_VIRTDESKTOP: 1
    plugs:
      - home
      - network
      # - network-bind
      - opengl
      - audio-playback
      # - joystick
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier-core:
    plugin: make
    source: https://github.com/n8marti/sommelier-core.git # use own repo for MSI installer
    # source-branch: "1.0"
    override-prime: |
      snapcraftctl prime

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # Remove annoying yad dialog for interactive MSI install.
      sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier


# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime

  wine-6-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-stable
