
  name: test-1984
  version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Troubleshoot a Telecel modem connection. # 79 char long summary
  description: |
    Perform various tests to identify why your Telecel modem connection
    is not working properly.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    app:
      # See 'snapcraft plugins'
      plugin: python3
      source: modem-check/.
  
