
name: test-1984
version: '1.0'
summary: This is a shell project for testing packaging viability.

description: |
  This is a shell project for testing packaging viability.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
base: core18
architectures:
  - amd64
# layout:

apps:
  saymore:
    command: bin/saymore
    # environment:
    extensions:
      - gnome-3-28
    plugs:
      - dotnet-runtime-50:dotnet-runtime
      - home
      - network
      - removable-media

parts:
  saymore:
    source: https://github.com/sillsdev/saymore.git
    plugin: nil
    build-packages:
      - mono-devel
      - wget
    build-snaps:
      - dotnet-sdk
    override-pull: |
      mkdir -p build/.nuget
      wget -P build/.nuget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      snapcraftctl pull
    #   build/getDependencies-windows.sh
    override-build: |
      chmod +x build/.nuget/nuget.exe
      # mv build/.nuget/nuget.exe build/.nuget/NuGet.exe
      dotnet build SayMore.sln
    stage-packages:
      - mono-runtime
    stage-snaps:
      - dotnet-runtime-50
