
name: test-1984
version: '1.0'
summary: This is a shell project for testing packaging viability.

description: |
  This is a shell project for testing packaging viability.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
architectures:
  - amd64
# layout:

apps:
  saymore:
    command: bin/saymore
    # environment:
    extensions:
      - gnome-3-28
    plugs:
      - dotnet-runtime-50:dotnet-runtime
      - home
      - network
      - removable-media

parts:
  saymore:
    source: https://github.com/sillsdev/saymore
    stage-snaps:
      - dotnet-runtime-50
