
  name: test-1984
  version: '1.0'
  summary: A simple backup GUI for version backups to an external USB device.

  description: |
    Wasta-Backup will auto-launch when a USB device with a previous
    Wasta-Backup on it is inserted.

    Restore possibilities include restoring previous versions of existing
    files or folders as well as restoring deleted files or folders from the
    backup device. In the case of restoring previous versions of existing
    items, the current item is first renamed using the current date and time.

    Additionally, a 'Restore ALL' option is available that will replace all
    data on the computer from the backup device.

    The following configurable settings are stored in a user's
    ~/.config/wasta-backup/ directory
        + backupDirs.txt - specifies directories to backup and other parameters
          such as number of versions to keep
        + backupInclude.txt - specifies file extensions to backup (so files
          with media extensions, etc., will be politely ignored)

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
  architectures:
    - amd64

  apps:
    wasta-backup:
      command: desktop-launch wasta-backup
      environment:
        "HOME": "$SNAP_USER_COMMON"
      plugs:
        - home
        - removable-media

  parts:
    wasta-backup:
      plugin: dump
      source: .
      after: [desktop-qt4]
      stage-packages:
        - libatk-adaptor
        - libgail-common
        - libgcc1
        - libqt4-network
        - libqtdbus4
        - libqt4-test
        - libqtcore4
        - libglib2.0-0
        - libqtgui4
        - libstdc++6
        - rdiff-backup
        - rsync
        - zlib1g
